apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prasuti-services-dev
  namespace: dev
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: services-dev.prasuti.ai
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prasuti-services
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prasuti-mail-dev
  namespace: dev
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: mail-dev.prasuti.ai
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prasuti-mail
            port:
              number: 80
